# To update this file refer to
#   https://github.com/MacPython/scipy-wheels/blob/master/.travis.yml
env:
    global:
        - REPO_DIR=scikit-misc
        - BUILD_COMMIT=v0.1.1
        - PLAT=x86_64
        - NP_BUILD_DEP="numpy==1.13.3"
        - NP_TEST_DEP="numpy==1.13.3"
        - CYTHON_BUILD_DEP="Cython==0.29.14"
        - PYBIND11_BUILD_DEP="pybind11==2.4.3"
        - UNICODE_WIDTH=32
        - WHEELHOUSE_UPLOADER_USERNAME=travis-worker
        - ENCRYPTION_LABEL=189e52c2c347

os: linux
language: python
# The travis Python version is unrelated to the version we build and test
# with.  This is set with the MB_PYTHON_VERSION variable.
python: 3.5
dist: trusty
services: docker

git:
  depth: 3

notifications:
   email:
      on_success: change
      on_failure: change

jobs:
  include:
    # linux, Python 3.6, 3.7, 3.8
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.6
        - NP_BUILD_DEP=numpy==1.13.3
        - NP_TEST_DEP=numpy==1.13.3
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.6
        - PLAT=i686
        - NP_BUILD_DEP=numpy==1.13.3
        - NP_TEST_DEP=numpy==1.13.3
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.7
        - NP_BUILD_DEP=numpy==1.14.5
        - NP_TEST_DEP=numpy==1.14.5
        - CYTHON_BUILD_DEP="Cython"
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.7
        - PLAT=i686
        - NP_BUILD_DEP=numpy==1.14.5
        - NP_TEST_DEP=numpy==1.14.5
        - CYTHON_BUILD_DEP="Cython"
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.8
        - NP_BUILD_DEP=numpy==1.17.3
        - NP_TEST_DEP=numpy==1.17.3
        - CYTHON_BUILD_DEP="Cython"
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.8
        - PLAT=i686
        - NP_BUILD_DEP=numpy==1.17.3
        - NP_TEST_DEP=numpy==1.17.3
        - CYTHON_BUILD_DEP="Cython"

    # OSX, Python 3.6, 3.7, 3.8
    - os: osx
      language: generic
      env:
        - MB_PYTHON_VERSION=3.6
        - NP_BUILD_DEP=numpy==1.13.3
        - NP_TEST_DEP=numpy==1.13.3
    - os: osx
      language: generic
      env:
        - MB_PYTHON_VERSION=3.7
        - NP_BUILD_DEP=numpy==1.14.5
        - NP_TEST_DEP=numpy==1.14.5
        - CYTHON_BUILD_DEP="Cython"
    - os: osx
      language: generic
      osx_image: xcode10.1
      env:
        - MB_PYTHON_VERSION=3.8
        - NP_BUILD_DEP=numpy==1.17.3
        - NP_TEST_DEP=numpy==1.17.3
        - CYTHON_BUILD_DEP="Cython"
        - MB_PYTHON_OSX_VER=10.9

before_install:
    - BUILD_DEPENDS="$NP_BUILD_DEP $CYTHON_BUILD_DEP $PYBIND11_BUILD_DEP"
    - TEST_DEPENDS="$NP_TEST_DEP pytest pytest-xdist pytest-faulthandler pytest-env"
    - source multibuild/common_utils.sh
    - source multibuild/travis_steps.sh
    - before_install

install:
    # Maybe get and clean and patch source
    - clean_code $REPO_DIR $BUILD_COMMIT
    - build_wheel $REPO_DIR $PLAT

script:
    - install_run $PLAT

after_success:
    - ./tools/commit_wheel.sh
