# Ref: https://github.com/python-pillow/pillow-wheels/blob/main/.github/workflows/wheels.yml
name: Wheels

on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - main
      - gh-actions

env:
  # BUILD_COMMIT: v0.1.4
  COMMIT_TOOLS_DIR: "${{ github.workspace }}/../commit_tools"
  WHEELS_BRANCH: "wheelhouse"
  WHEELHOUSE_DIR: "${{ github.workspace }}/../wheelhouse"

jobs:
  # linux:
  #   if: "!contains(github.event.head_commit.message, '[skip ci]') && always()"
  #   uses: ./.github/workflows/wheels-linux.yml
  #   with:
  #     artifacts-name: "wheels"
  #     wheelhouse-path: "wheelhouse/*"
  #     build-commit: "v0.1.4"
  #
  # macos:
  #   if: "!contains(github.event.head_commit.message, '[skip ci]') && always()"
  #   uses: ./.github/workflows/wheels-macos.yml
  #   with:
  #     artifacts-name: "wheels"
  #     wheelhouse-path: "wheelhouse/*"
  #     build-commit: "v0.1.4"

  macosx_arm64:
    if: "!contains(github.event.head_commit.message, '[skip ci]') && always()"
    uses: ./.github/workflows/wheels-macos_arm64.yml
    with:
      artifacts-name: "wheels"
      wheelhouse-path: "wheelhouse/*"
      build-commit: "v0.1.4"

  collect-wheels:
    name: Collect Wheels
    # needs: [linux, macos, macos-arm64]
    needs: [macosx_arm64]
    runs-on: ubuntu-latest
    steps:
      - name: Download all wheels
        uses: actions/download-artifact@v2
        with:
          name: wheels
          path: "${{ env.WHEELHOUSE_DIR }}"

      - name: Contents of wheelhouse directory
        shell: bash -l {0}
        run: ls -la "$WHEELHOUSE_DIR"

      - name: Checkout main repository
        uses: actions/checkout@v2

      - name: Copy commit tools from main repository
        run: |
          mkdir -p "$COMMIT_TOOLS_DIR"
          cp tools/commit_wheels.sh "$COMMIT_TOOLS_DIR"

      - name: Checkout wheelhouse branch
        uses: actions/checkout@v2
        with:
          ref: ${{ env.WHEELS_BRANCH }}

      - name: Commit wheels
        shell: bash -l {0}
        run : source "$COMMIT_TOOLS_DIR/commit_wheels.sh"
