# Ref: https://github.com/python-pillow/pillow-wheels/blob/main/.github/workflows/wheels-macos.yml
name: Build macOS  wheels

env:
  REPO_DIR: scikit-misc
  CYTHON_BUILD_DEP: "Cython==0.29.24"
  BUILD_DIR: ${{ github.workspace }}
  OTHER_TEST_DEPS: "pytest"

on:
  workflow_call:
    inputs:
      artifacts-name:
        required: true
        type: string
      wheelhouse-path:
        required: true
        type: string

jobs:
  build:
    runs-on: "macos-latest"
    strategy:
      fail-fast: false
      matrix:
        platform: ["x86_64", "arm64"]
        python: ["3.9", "3.10"]

    env:
      PLAT: ${{ matrix.platform }}
      TRAVIS_OS_NAME: "osx"
      MB_PYTHON_VERSION: ${{ matrix.python }}
      NP_BUILD_DEP: oldest-supported-numpy
      NP_TEST_DEP: oldest-supported-numpy

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}

      - name: Build Wheel
        shell: bash -l {0}
        run: |
          pip install --upgrade pip
          source .github/workflows/build.sh

      - name: List files
        shell: bash -l {0}
        run : ls -la wheelhouse

      - name: Upload Wheel
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifacts-name }}
          path: ${{ inputs.wheelhouse-path }}
